### ISSUE TITLE
Suggestion - Make amd64 default

### ISSUE THREAD

**Issue by christianhals** [iusvar/grav-plugin-snappygrav#33]
This is more of a suggestion and not a bug. I just updated to latest 1.62 version and see that I have lost my wkhtmltopdf-amd64 directory from 1.61 version  under vendor/h4cc . 

If you are running Grav in a cloud datacenter most providers will give you an x64 system. Maybe it would be better to make this the default setup? Or include both x32 and x64 in the package.

**Comment by iusvar** [comment]
Thanks for the suggestion, I will think about it

**Comment by axza** [comment]
wkhtmltopdf-amd64 0.12.4 didn't worked here.. 0.12.5 does ☺️

**Comment by iusvar** [comment]
I am aware that the latest version compiled (https://wkhtmltopdf.org/downloads.html) is the 0.12.5 but ... it is not available by composer from the usual https://github.com/h4cc

However, only for this time, I have procured the executables that I have placed in the respective folders, so there is no need to run composer otherwise the 0.12.4 versions would be restored.

For the future, I could abandon wkhtmltopdf for an all-php engine like mpdf for example. I'll think about it.

Version 1.8.0 released
